### ISSUE TITLE
Airdrop 页面 claim 优化

### ISSUE THREAD

**Issue by jiangydev** [starcoinorg/starcoin-airdrop#4]
两个建议:
1. claim 之后，交易成功后页面能不能刷一下（虽然有系统通知），按钮颜色一直不变，海外用户不知道是否成功，一直会去点按钮。
2. 已经领过的空投，按钮能不能置灰，或弹窗提示“您已经领取”，有个海外用户昨天就领了，今天说点按钮没反应。

**Comment by tarvos21** [comment]
Reply:

1. 加了刷新功能，但状态改变取决于交易是否执行成功，刷新后并不保证按钮状态会改变
2. 对于已经领取空投的用户，按钮已经改为灰色，并且无法点击
